site_name: "EMR Containers Best Practices Guides"
repo_name: "aws/aws-emr-containers-best-practices"
repo_url: "https://github.com/aws/aws-emr-containers-best-practices"
docs_dir: "content"
theme:
  name: material
  features:
    - navigation.tabs
nav:
  - Guides:
      - Introduction: 'index.md'
  - Security:
      - Home: 'security/docs/index.md'
      - Data Encryption: 'security/docs/spark/data-encryption.md'
      - Network Security: 'security/docs/spark/network-security.md'
  - Submit Spark applications:
      - Home: 'submit-applications/docs/index.md'
      - Java and Scala: 'submit-applications/docs/java-and-scala.md'
      - Pyspark: 'submit-applications/docs/pyspark.md'
      - SparkR: 'submit-applications/docs/sparkr.md'
      - SparkSQL: 'submit-applications/docs/sparksql.md'
  - Storage:
      - Home: 'storage/docs/index.md'
      - EBS: 'storage/docs/spark/ebs.md'
      - FSx for Lustre: 'storage/docs/spark/fsx-lustre.md'
  - Metastore Integration:
      - Home: 'metastore-integration/docs/index.md'
      - Hive Metastore: 'metastore-integration/docs/hive-metastore.md'
      - AWS Glue: 'metastore-integration/docs/aws-glue.md'
  - Debugging:
      - Home: 'debugging/docs/index.md'
      - Change Log Level: 'debugging/docs/change-log-level.md'
  - Node Placement:
      - Home: 'node-placement/docs/index.md'
      - EKS Node placement: 'node-placement/docs/eks-node-placement.md'
      - Fargate Node placement: 'node-placement/docs/fargate-node-placement.md'
  - Performance:
      - Home: 'performance/docs/index.md'
      - Dynamic Resource Allocation: 'performance/docs/dra.md'
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite